### ISSUE TITLE
when we can use it 

### ISSUE THREAD

**Issue by pretech86** [0x4xLEAKR/DarkCrypter#1]
thanks for your efforts , but when we can use it  ?

hope to finish it soon, thanks a lot

**Comment by yugdrix** [comment]
Hello it doesnt work. is it normal. even with the source code compiled.

**Comment by enzio53** [comment]
Hi, everyone it's fucking rat.

Creating in background application nodejs-daemon.exe stored AppData\Roaming\ProfessionalSQLite3 Samples\nodejs-daemon.exe

Pointing at 149.167.94.36:9001 🌡️

**Comment by 0-x27** [comment]
nah bro it's legit.
